import{S as p,i as g}from"./assets/vendor-46aac873.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const d="/goit-js-hw-12/assets/alert-6c35a70b.svg",y="https://pixabay.com/api/",c={key:"41933677-6eee14a43ac3f23b8d77fa6f0",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:18},m=document.querySelector(".form"),u=document.querySelector(".searchTerm"),h=document.querySelector(".search-btn"),w=document.querySelector(".loader"),f=document.querySelector(".gallery"),b=new p(".gallery a",{overlayOpacity:.8,captionsData:"alt",captionDelay:250});m?m.addEventListener("submit",s=>{if(s.preventDefault(),u.value.trim().length<3){l("Please, enter search term!");return}S().then(t=>v(t)).catch(t=>l(t.toString()))}):console.error("Element with class .form not found");function S(){f.textContent="",o(!0),c.q=u.value.trim();const s=new URLSearchParams(c);return fetch(`${y}?${s}`).then(t=>{if(!t.ok)throw new Error(t.status);try{return t.json()}catch{throw new Error("Failed to parse JSON")}})}function v(s){if(s.total===0){l("Sorry, there are no images matching your search query. Please try again!"),o(!1);return}const t=s.hits.map(a=>`<a class="gallery-link" href="${a.largeImageURL}"><span class="gallery-item"><img class="gallery-image" src="${a.webformatURL}" alt="${a.tags}" title="${a.tags}" /></span>
            <span class="img-stat">
            <span class="img-stat-item"><span class="img-stat-title">Likes</span><span class="img-stat-val">${a.likes}</span></span>
            <span class="img-stat-item"><span class="img-stat-title">Views</span><span class="img-stat-val">${a.views}</span></span>
            <span class="img-stat-item"><span class="img-stat-title">Comments</span><span class="img-stat-val">${a.comments}</span></span>
            <span class="img-stat-item"><span class="img-stat-title">Downloads</span><span class="img-stat-val">${a.downloads}</span></span>
            </span>
            </a>`).join("");o(!1),f.insertAdjacentHTML("beforeend",t),b.refresh()}function o(s=!0){w.style.display=s?"inline-block":"none",h.disabled=s}function l(s){g.show({position:"center",iconUrl:d,messageColor:"#FAFAFB",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0,message:s})}
//# sourceMappingURL=commonHelpers.js.map
